Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1107, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pyreadr
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stopwords = list(stopwords.words('english'))

data = pyreadr.read_r('data/sotu_all.rda') 

df = data['sotu_all']

def clean_text(df):
    docs = []
    for index in df.index:
        speech = df.loc[index, 'speechtext']
        text = ''.join(speech)
        words = word_tokenize(text)
        words = [word.replace(" ", "") for word in words]
        words = [word.lower() for word in words if word.isalpha()]
        words = [word for word in words if word not in stopwords]
        df.loc[index, 'speechtext'] = words
        docs.append(words)
    return docs, df

docs, df = clean_text(df)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mPyreadrError[0m                              Traceback (most recent call last)
[0;32m<ipython-input-18-4118bc15e1e7>[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0mstopwords[0m [0;34m=[0m [0mlist[0m[0;34m([0m[0mstopwords[0m[0;34m.[0m[0mwords[0m[0;34m([0m[0;34m'english'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m
[0;32m----> 6[0;31m [0mdata[0m [0;34m=[0m [0mpyreadr[0m[0;34m.[0m[0mread_r[0m[0;34m([0m[0;34m'data/sotu_all.rda'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0;34m[0m[0m
[1;32m      8[0m [0mdf[0m [0;34m=[0m [0mdata[0m[0;34m[[0m[0;34m'sotu_all'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.9/site-packages/pyreadr/pyreadr.py[0m in [0;36mread_r[0;34m(path, use_objects, timezone)[0m
[1;32m     45[0m     [0mpath[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mexpanduser[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     46[0m     [0;32mif[0m [0;32mnot[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0misfile[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 47[0;31m         [0;32mraise[0m [0mPyreadrError[0m[0;34m([0m[0;34m"File {0} does not exist!"[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     48[0m     [0mparser[0m[0;34m.[0m[0mparse[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     49[0m [0;34m[0m[0m

[0;31mPyreadrError[0m: File data/sotu_all.rda does not exist!
PyreadrError: File data/sotu_all.rda does not exist!

